# Site
repository: sproogen/resume-theme
# favicon: images/favicon.ico

# Personal info
name: Brett Larson
title: Site Reliability Engineer
email: brettpatricklarson@gmail.com
website: https://brettplarson.github.io/

# Social links
twitter_username: ___brett_
github_username: brettplarson
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: chillwildlife
linkedin_username: brettplarson
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.png
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Brett - I’m a sysadmin / DevOps Engineer / Site Reliability Engineer (SRE) / NOC engineer / wanna-be programmer who lives in the Chicagoland area.

  I have more than ten years of relevant experience with some of the best Managed Service providers and IT shops in the area.

  My current focus is on Kubernetes, Python in the context of data science and Azure. 

  I am most skilled in: <mark>observability</mark> and <mark>troubleshooting complex systems.</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education


# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
