# Site
repository: sproogen/resume-theme
# favicon: images/favicon.ico

# Personal info
name: Brett Larson
title: Site Reliability Engineer
email: brettpatricklarson@gmail.com
website: https://brettplarson.github.io/

# Social links
twitter_username: ___brett_
github_username: brettplarson
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: chillwildlife
linkedin_username: brettplarson
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.png
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Brett - I’m a DevOps Engineer / Site Reliability Engineer (SRE) who lives in the Chicagoland area.

  My current focus is on Kubernetes, Python and AWS and Azure clouds.

  I am most skilled in: <mark>observability</mark> and <mark>troubleshooting complex systems.</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education


# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
